# Generated by Django 4.0 on 2021-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_skill_alter_role_id_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'BLOGER'), (4, 'employee'), (5, 'admin')], primary_key=True, serialize=False),
        ),
    ]
