# Generated by Django 4.0 on 2021-12-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'teacher'), (3, 'bloger'), (4, 'employee'), (5, 'admin')], primary_key=True, serialize=False),
        ),
    ]
