# Generated by Django 4.0 on 2021-12-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
