# Generated by Django 4.0 on 2021-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_category_faq_cats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
